export const OBSERVATION_LOADING = "OBSERVATION_LOADING"
export const OBSERVATION_FAIL = "OBSERVATION_FAIL"
export const OBSERVATION_SUCCESS = "OBSERVATION_SUCCESS"

export const LOCATION_LOADING = "LOCATION_LOADING"
export const LOCATION_FAIL = "LOCATION_FAIL"
export const LOCATION_SUCCESS = "LOCATION_SUCCESS"